languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "DaveSaah's Portfolio"

[params]
dateFormat = "2 January 2006"

description = "Portfolio website of David Saah, Backend/Systems Engineer & CLI Junkie"

[params.author]
name = "David Saah"
image = "img/author.jpeg"
headline = "Backend/Systems Engineer & CLI Junkie"
bio = "Portfolio website of David Saah, Backend/Systems Engineer & CLI Junkie"
links = [
  { email = "mailto:davesaah@gmail.com" },
  { github = "https://github.com/DaveSaah" },
  { x-twitter = "https://x.com/davesaah_" },
  { linkedin = "https://linkedin.com/in/davesaah" },
]
